import 'package:site_buddy/features/structural/slab/domain/slab_type.dart';

/// MODEL: SlabInput
/// Data structure for all inputs required to perform a slab design.
class SlabInput {
  final SlabType type;
  final double lx; // in m
  final double ly; // in m
  final double depth; // in mm
  final double deadLoad; // in kN/m2
  final double liveLoad; // in kN/m2
  final String concreteGrade;
  final String steelGrade;
  final double cover; // in mm

  const SlabInput({
    required this.type,
    required this.lx,
    required this.ly,
    required this.depth,
    required this.deadLoad,
    required this.liveLoad,
    this.concreteGrade = 'M25',
    this.steelGrade = 'Fe500',
    this.cover = 20.0,
  });
}

/// MODEL: SlabResult
/// Data structure for all outputs generated by an RCC slab design.
class SlabResult {
  final double bendingMoment;
  final String mainRebar;
  final String distributionSteel;
  final bool isShearSafe;
  final bool isDeflectionSafe;
  final bool isCrackingSafe;
  final double astProvided;
  final double astRequired;

  const SlabResult({
    required this.bendingMoment,
    required this.mainRebar,
    required this.distributionSteel,
    this.isShearSafe = true,
    this.isDeflectionSafe = true,
    this.isCrackingSafe = true,
    this.astProvided = 0,
    this.astRequired = 0,
  });
}

