import 'package:site_buddy/features/structural/footing/domain/footing_type.dart';

/// MODEL: FootingInput
/// Data structure for all inputs required to perform a footing design.
class FootingInput {
  final FootingType type;
  final double columnLoad; // in kN
  final double sbc; // Safe Bearing Capacity in kN/m2
  final double footingLength; // in mm
  final double footingWidth; // in mm
  final double footingThickness; // in mm
  final String concreteGrade;
  final String steelGrade;
  final double momentX; // in kNm
  final double momentY; // in kNm
  final double foundationDepth; // in m
  final double mainBarDia; // in mm

  const FootingInput({
    required this.type,
    required this.columnLoad,
    required this.sbc,
    required this.footingLength,
    required this.footingWidth,
    required this.footingThickness,
    required this.concreteGrade,
    required this.steelGrade,
    this.momentX = 0,
    this.momentY = 0,
    this.foundationDepth = 1.5,
    this.mainBarDia = 12.0,
  });
}

/// MODEL: FootingResult
/// Data structure for all outputs generated by an RCC footing design.
class FootingResult {
  final double areaRequired;
  final double providedArea;
  final double maxSoilPressure;
  final double minSoilPressure;
  final bool isAreaSafe;
  final double muX;
  final double muY;
  final double astRequiredX;
  final double astRequiredY;
  final double astProvidedX;
  final double astProvidedY;
  final double mainBarSpacing;
  final double crossBarSpacing;
  final double shearForceOneWay;
  final double shearForcePunching;
  final bool isOneWayShearSafe;
  final bool isPunchingShearSafe;
  final bool isBendingSafe;

  const FootingResult({
    required this.areaRequired,
    required this.providedArea,
    required this.maxSoilPressure,
    required this.minSoilPressure,
    required this.isAreaSafe,
    required this.muX,
    required this.muY,
    required this.astRequiredX,
    required this.astRequiredY,
    required this.astProvidedX,
    required this.astProvidedY,
    required this.mainBarSpacing,
    required this.crossBarSpacing,
    required this.shearForceOneWay,
    required this.shearForcePunching,
    required this.isOneWayShearSafe,
    required this.isPunchingShearSafe,
    required this.isBendingSafe,
  });
}

