/// FILE HEADER
/// ----------------------------------------------
/// File: pdf_generator.dart
/// Feature: core/utils
/// Layer: utilities
///
/// PURPOSE:
/// Generates a standardized PDF Document containing the structured AI Answer content.
///
/// RESPONSIBILITIES:
/// - Maps the Question and Answer to a `pdf` widget layout.
/// - Opens the native printing/PDF spooler dialog to export the payload.
/// ----------------------------------------------
library;


import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';

class PdfGenerator {
  /// METHOD: generateAndSharePdf
  /// PURPOSE: Constructs a PDF layout and triggers the device's native PDF export/print dialog.
  /// WHY: Offloads heavy document creation outside of the UI context safely.
  static Future<void> generateAndSharePdf({
    required String question,
    required String answer,
    required String projectName,
  }) async {
    final pdf = pw.Document();
    final String formattedDate = _formattedDate();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Container(
                decoration: const pw.BoxDecoration(
                  border: pw.Border(
                    bottom: pw.BorderSide(color: PdfColors.grey400, width: 2),
                    top: pw.BorderSide(color: PdfColors.grey400, width: 2),
                  ),
                ),
                padding: const pw.EdgeInsets.symmetric(vertical: 12.0),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      'SITE BUDDY REPORT',
                      style: pw.TextStyle(
                        fontSize: 20,
                        fontWeight: pw.FontWeight.bold,
                      ),
                    ),
                    pw.SizedBox(height: 4),
                    pw.Text(
                      'Project: $projectName',
                      style: pw.TextStyle(
                        fontSize: 14,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.grey700,
                      ),
                    ),
                    pw.SizedBox(height: 2),
                    pw.Text(
                      'Date: $formattedDate',
                      style: const pw.TextStyle(
                        fontSize: 12,
                        color: PdfColors.grey600,
                      ),
                    ),
                  ],
                ),
              ),
              pw.SizedBox(height: 24),
              pw.Text(
                'Question:',
                style: pw.TextStyle(
                  fontSize: 16,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 8),
              pw.Text(question, style: const pw.TextStyle(fontSize: 14)),
              pw.SizedBox(height: 24),
              pw.Text(
                'Answer:',
                style: pw.TextStyle(
                  fontSize: 16,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 8),
              pw.Text(answer, style: const pw.TextStyle(fontSize: 14)),
              pw.Spacer(),
              pw.Container(
                decoration: const pw.BoxDecoration(
                  border: pw.Border(
                    top: pw.BorderSide(color: PdfColors.grey400, width: 2),
                    bottom: pw.BorderSide(color: PdfColors.grey400, width: 2),
                  ),
                ),
                padding: const pw.EdgeInsets.symmetric(vertical: 8.0),
                child: pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text(
                      'Generated by Site Buddy',
                      style: pw.TextStyle(
                        fontSize: 12,
                        fontWeight: pw.FontWeight.bold,
                        color: PdfColors.grey800,
                      ),
                    ),
                    pw.SizedBox(height: 2),
                    pw.Text(
                      'Developed by Er. Pijush Debbarma',
                      style: const pw.TextStyle(
                        fontSize: 10,
                        color: PdfColors.grey600,
                      ),
                    ),
                  ],
                ),
              ),
            ],
          );
        },
      ),
    );

    // This immediately triggers the native print dialog allowing "Save as PDF" or physical printing
    await Printing.layoutPdf(
      onLayout: (PdfPageFormat format) async => pdf.save(),
      name: 'SiteBuddy_Report_${DateTime.now().millisecondsSinceEpoch}.pdf',
    );
  }

  static String _formattedDate() {
    final now = DateTime.now();
    final months = [
      'Jan',
      'Feb',
      'Mar',
      'Apr',
      'May',
      'Jun',
      'Jul',
      'Aug',
      'Sep',
      'Oct',
      'Nov',
      'Dec',
    ];
    return '${now.day} ${months[now.month - 1]} ${now.year}';
  }
}
