

import 'package:site_buddy/core/widgets/sb_widgets.dart';

import 'package:site_buddy/core/theme/app_spacing.dart';

/// FILE HEADER
/// ----------------------------------------------
/// File: ai_share_report_card.dart
/// Feature: ai_assistant
/// Layer: presentation/widgets
///
/// PURPOSE:
/// Responsible for rendering a professional, engineering-grade visual report block.
///
/// RESPONSIBILITIES:
/// - Reusable for visual presentation inside Preview boundaries and Image renders.
/// - Hard constraints outer padding (6px) matching the strict layout specification.
/// ----------------------------------------------

import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

class AiShareReportCard extends StatelessWidget {
  final String question;
  final String answer;
  final String projectName;

  const AiShareReportCard({
    super.key,
    required this.question,
    required this.answer,
    required this.projectName,
  });

  String _formattedDate() {
    return DateFormat('dd MMM yyyy').format(DateTime.now());
  }

  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);
    
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: AppSpacing.sm),
      child: SbCard(
        padding: const EdgeInsets.all(AppSpacing.lg),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          mainAxisSize: MainAxisSize.min, // Keep card wrapped safely around text
          children: [
            // HEADER
            Container(
              padding: const EdgeInsets.only(bottom: AppSpacing.sm),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'SITE BUDDY REPORT',
                    style: theme.textTheme.bodyMedium?.copyWith(
                          fontWeight: FontWeight.w500,
                        ),

                  ),
                  const SizedBox(height: AppSpacing.xs),
                  Text(
                    'Project: $projectName',
                    style: theme.textTheme.labelMedium!,
                  ),
                  Text(
                    'Date: ${_formattedDate()}',
                    style: theme.textTheme.bodyMedium!,
                  ),
                ],
              ),
            ),
            const SizedBox(height: AppSpacing.lg),

            // BODY: Question
            Text(
              'Question:',
              style: theme.textTheme.bodyMedium?.copyWith(
                    fontWeight: FontWeight.w500,
                  ),

            ),
            const SizedBox(height: AppSpacing.sm),
            Text(question, style: theme.textTheme.bodyLarge!),

            const SizedBox(height: AppSpacing.lg),

            // BODY: Answer
            Text(
              'Answer:',
              style: theme.textTheme.bodyMedium?.copyWith(
                    fontWeight: FontWeight.w500,
                  ),

            ),
            const SizedBox(height: AppSpacing.sm),
            Text(answer, style: theme.textTheme.bodyLarge!),

            const SizedBox(height: AppSpacing.lg),

            // FOOTER BRANDING
            Container(
              padding: const EdgeInsets.only(top: AppSpacing.sm),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Generated by Site Buddy',
                    style: theme.textTheme.bodyMedium!,
                  ),
                  Text(
                    'Developed by Er. Pijush Debbarma',
                    style: theme.textTheme.bodyMedium!,
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}








