import 'package:site_buddy/core/design_system/sb_text_styles.dart';

import 'package:site_buddy/core/widgets/sb_widgets.dart';

import 'package:site_buddy/core/theme/app_layout.dart';

/// FILE HEADER
/// ----------------------------------------------
/// File: ai_share_report_card.dart
/// Feature: ai_assistant
/// Layer: presentation/widgets
///
/// PURPOSE:
/// Responsible for rendering a professional, engineering-grade visual report block.
///
/// RESPONSIBILITIES:
/// - Reusable for visual presentation inside Preview boundaries and Image renders.
/// - Hard constraints outer padding (6px) matching the strict layout specification.
/// ----------------------------------------------

import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

class AiShareReportCard extends StatelessWidget {
  final String question;
  final String answer;
  final String projectName;

  const AiShareReportCard({
    super.key,
    required this.question,
    required this.answer,
    required this.projectName,
  });

  String _formattedDate() {
    return DateFormat('dd MMM yyyy').format(DateTime.now());
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: AppLayout.pSmall),
      child: SbCard(
        padding: const EdgeInsets.all(AppLayout.pMedium),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          mainAxisSize:
              MainAxisSize.min, // Keep card wrapped safely around text
          children: [
            // HEADER
            Container(
              padding: const EdgeInsets.only(bottom: AppLayout.pSmall),

              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'SITE BUDDY REPORT',
                    style: SbTextStyles.title(context).copyWith(
                      letterSpacing: 1.2,
                      color: Theme.of(context).colorScheme.onSurface,
                    ),
                  ),
                  const SizedBox(height: AppLayout.pTiny),
                  Text(
                    'Project: $projectName',
                    style: SbTextStyles.caption(context).copyWith(
                      color: Theme.of(context).colorScheme.onSurface,
                    ),
                  ),
                  Text(
                    'Date: ${_formattedDate()}',
                    style: SbTextStyles.bodySecondary(context).copyWith(color: Colors.grey),
                  ),
                ],
              ),
            ),
            AppLayout.vGap16,

            // BODY: Question
            Text(
              'Question:',
              style: SbTextStyles.title(context).copyWith(
                color: Theme.of(context).colorScheme.onSurface,
              ),
            ),
            AppLayout.vGap8,
            Text(question, style: SbTextStyles.body(context)),

            AppLayout.vGap16,

            // BODY: Answer
            Text(
              'Answer:',
              style: SbTextStyles.title(context).copyWith(
                color: Theme.of(context).colorScheme.onSurface,
              ),
            ),
            AppLayout.vGap8,
            Text(answer, style: SbTextStyles.body(context)),

            AppLayout.vGap16,

            // FOOTER BRANDING
            Container(
              padding: const EdgeInsets.only(top: AppLayout.pSmall),

              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    'Generated by Site Buddy',
                    style: SbTextStyles.bodySecondary(context).copyWith(color: Colors.grey),
                  ),
                  Text(
                    'Developed by Er. Pijush Debbarma',
                    style: SbTextStyles.bodySecondary(context).copyWith(
                      color: Colors.grey.withValues(alpha: 0.8),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}