from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession
from app.core.database import get_db
from app.api.dependencies import get_current_user
from app.models.user import User
from app.repositories.report_repository import ReportRepository
from app.schemas.report_schema import Report, ReportCreate
from app.schemas.response_schema import ApiResponse, success_response
from typing import List
import uuid

router = APIRouter(tags=["Reports"])

@router.get(
    "/", 
    response_model=ApiResponse[List[Report]],
    summary="List All Reports",
    description="Retrieves a list of all engineering reports generated by the user."
)
async def list_reports(
    page: int = 1,
    limit: int = 20,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    report_repo = ReportRepository(db)
    skip = (page - 1) * limit
    reports = await report_repo.get_by_user(current_user.id, skip=skip, limit=limit)
    return success_response(data=reports, message="Reports retrieved successfully")

@router.post(
    "/", 
    response_model=ApiResponse[Report],
    summary="Create Report Metadata",
    description="Saves metadata for a newly generated engineering report, including its Google Drive file ID."
)
async def create_report(
    report_in: ReportCreate,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    report_repo = ReportRepository(db)
    report_data = report_in.dict()
    report_data["user_id"] = current_user.id
    if not report_data.get("id"):
        report_data["id"] = str(uuid.uuid4())
    else:
        report_data["id"] = str(report_data["id"])
    
    report_data["project_id"] = str(report_data["project_id"])
    
    report = await report_repo.create(obj_in=report_data)
    return success_response(data=report, message="Report metadata saved successfully")

@router.get(
    "/{id}", 
    response_model=ApiResponse[Report],
    summary="Get Report Details",
    description="Retrieves metadata for a specific engineering report by its ID."
)
async def get_report(
    id: str, 
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    report_repo = ReportRepository(db)
    report = await report_repo.get(id)
    if not report or report.user_id != current_user.id:
        raise HTTPException(status_code=404, detail="Report not found")
    return success_response(data=report, message="Report retrieved successfully")
