import 'package:site_buddy/features/report/domain/report_section.dart';

/// MODEL: EngineeringReport
/// PURPOSE: Unified model for all engineering reports (Structural, Road, Irrigation).
class EngineeringReport {
  final String id;
  final String title;
  final String projectTitle;
  final String engineerName;
  final DateTime date;
  final String codeReference; // e.g., "IS 456", "IRC 37"
  final List<ReportSection> sections;
  final String footerNote;
  final bool isPro;

  const EngineeringReport({
    required this.id,
    required this.title,
    required this.projectTitle,
    required this.engineerName,
    required this.date,
    required this.codeReference,
    required this.sections,
    this.footerNote = "Generated by SiteBuddy | Professional Engineering Suite",
    required this.isPro,
  });
}
