import 'dart:math' as math;
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:site_buddy/core/optimization/optimization_engine.dart';
import 'package:site_buddy/core/optimization/optimization_result.dart';
import 'package:site_buddy/shared/domain/models/design/column_design_state.dart';
import 'package:site_buddy/shared/domain/models/design/beam_design_state.dart';
import 'package:site_buddy/shared/domain/models/design/slab_design_state.dart';
import 'package:site_buddy/shared/domain/models/design/footing_design_state.dart';
import 'package:site_buddy/shared/domain/models/design/column_enums.dart';

/// SERVICE: DesignReportService
/// PURPOSE: Professional PDF report generation for structural design modules.
/// DESIGN: Provides shared layout components and orchestration for Column, Beam, Slab, and Footing reports.
class DesignReportService {
  static final _optimizationEngine = OptimizationEngine();

  static Future<void> generateAndShare({
    required String title,
    required String subtitle,
    required List<pw.Widget> content,
    String projectName = 'Unnamed Project',
    String? reference,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) => [
          _buildHeader(title, subtitle, projectName, reference),
          pw.SizedBox(height: 20),
          ...content,
          pw.Spacer(),
          _buildFooter(context),
        ],
      ),
    );

    await Printing.sharePdf(
      bytes: await pdf.save(),
      filename:
          '${title.replaceAll(' ', '_')}_Report_${DateTime.now().millisecondsSinceEpoch}.pdf',
    );
  }

  static pw.Widget _buildHeader(
    String title,
    String subtitle,
    String projectName,
    String? reference,
  ) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  'SITEBUDDY STRUCTURAL DESIGN',
                  style: pw.TextStyle(
                    fontSize: 10,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.blue800,
                  ),
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  title.toUpperCase(),
                  style: pw.TextStyle(
                    fontSize: 18,
                    fontWeight: pw.FontWeight.bold,
                    color: PdfColors.black,
                  ),
                ),
                pw.Text(
                  subtitle,
                  style: pw.TextStyle(
                    fontSize: 12,
                    color: PdfColors.grey700,
                    fontStyle: pw.FontStyle.italic,
                  ),
                ),
              ],
            ),
            pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.end,
              children: [
                pw.Text(
                  'Date: ${DateTime.now().toString().split(' ')[0]}',
                  style: const pw.TextStyle(fontSize: 10),
                ),
                if (reference != null)
                  pw.Text(
                    'Ref: $reference',
                    style: const pw.TextStyle(fontSize: 10),
                  ),
              ],
            ),
          ],
        ),
        pw.SizedBox(height: 10),
        pw.Divider(thickness: 1, color: PdfColors.blue800),
        pw.SizedBox(height: 10),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'PROJECT: $projectName',
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 11),
            ),
            pw.Text(
              'CODE: IS 456:2000',
              style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 11),
            ),
          ],
        ),
      ],
    );
  }

  static pw.Widget _buildFooter(pw.Context context) {
    return pw.Column(
      children: [
        pw.Divider(thickness: 0.5, color: PdfColors.grey400),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
          children: [
            pw.Text(
              'Generated by SiteBuddy v1.0 - Professional Engineering Tool',
              style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
            ),
            pw.Text(
              'Page ${context.pageNumber} of ${context.pagesCount}',
              style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500),
            ),
          ],
        ),
      ],
    );
  }

  // --- Helper Components for Reports ---

  static pw.Widget sectionTitle(String title) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 8.0),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            title.toUpperCase(),
            style: pw.TextStyle(
              fontSize: 12,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.blue900,
            ),
          ),
          pw.SizedBox(height: 2),
          pw.Container(height: 1, color: PdfColors.blue100),
        ],
      ),
    );
  }

  static pw.Widget infoTable(List<List<String>> data) {
    return pw.TableHelper.fromTextArray(
      data: data,
      cellAlignment: pw.Alignment.centerLeft,
      cellStyle: const pw.TextStyle(fontSize: 10),
      headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10),
      border: pw.TableBorder.all(color: PdfColors.grey200, width: 0.5),
      cellPadding: const pw.EdgeInsets.all(5),
    );
  }

  static pw.Widget safetyBadge(bool isSafe, String label) {
    return pw.Container(
      padding: const pw.EdgeInsets.symmetric(horizontal: 10, vertical: 5),
      decoration: pw.BoxDecoration(
        color: isSafe ? PdfColors.green100 : PdfColors.red100,
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
      ),
      child: pw.Text(
        label,
        style: pw.TextStyle(
          color: isSafe ? PdfColors.green900 : PdfColors.red900,
          fontWeight: pw.FontWeight.bold,
          fontSize: 10,
        ),
      ),
    );
  }

  static pw.Widget _buildOptimizationSection(OptimizationResult result) {
    final labels = ['Economical', 'Balanced', 'High Safety'];
    final descriptions = [
      'Minimum steel consumption',
      'Moderate utilization',
      'Lowest structural stress',
    ];

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        sectionTitle('5. Design Alternatives (AI Optimization)'),
        pw.Text(
          'The following options were generated based on structural efficiency and Indian Standard (IS 456) constraints.',
          style: pw.TextStyle(fontSize: 9, fontStyle: pw.FontStyle.italic),
        ),
        pw.SizedBox(height: 8),
        infoTable([
          ['Option Type', 'Configuration', 'Details', 'Utilization'],
          for (int i = 0; i < result.options.length; i++)
            [
              '${labels[i]}\n(${descriptions[i]})',
              result.options[i].title,
              result.options[i].description,
              '${(result.options[i].utilization * 100).toInt()}%',
            ],
        ]),
      ],
    );
  }

  static Future<void> generateColumnReport(ColumnDesignState state) async {
    final content = [
      sectionTitle('1. Input Parameters'),
      infoTable([
        ['Type', 'Dimensions', 'Concrete', 'Steel'],
        [
          state.type.label,
          '${state.b.toInt()} x ${state.d.toInt()} mm',
          state.concreteGrade,
          state.steelGrade,
        ],
      ]),
      pw.SizedBox(height: 10),
      infoTable([
        ['End Condition', 'Clear Cover', 'Unsupported Length'],
        [
          state.endCondition.label,
          '${state.cover} mm',
          '${(state.length / 1000).toStringAsFixed(2)} m',
        ],
      ]),
      sectionTitle('2. Applied Loads (Factored)'),
      infoTable([
        ['Load Case', 'Axial (Pu)', 'Moment (Mux)', 'Moment (Muy)'],
        [
          state.loadType.label,
          '${state.pu} kN',
          '${state.mx} kNm',
          '${state.my} kNm',
        ],
      ]),
      sectionTitle('3. Design Results & Safety'),
      pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'Interaction Ratio: ${state.interactionRatio.toStringAsFixed(3)}',
              ),
              pw.Text('Classification: ${state.isShort ? "Short" : "Slender"}'),
              pw.SizedBox(height: 5),
              safetyBadge(
                state.isCapacitySafe,
                'CAPACITY: ${state.isCapacitySafe ? "PASS" : "FAIL"}',
              ),
            ],
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text('Required Area: ${state.astRequired.toInt()} mm²'),
              pw.Text(
                'Steel Percentage: ${state.steelPercentage.toStringAsFixed(2)}%',
              ),
            ],
          ),
        ],
      ),
      sectionTitle('4. Reinforcement Detailing'),
      infoTable([
        ['Main Reinforcement', 'Lateral Ties'],
        [
          '${state.numBars} Nos ${state.mainBarDia.toInt()}mm dia',
          '${state.tieDia.toInt()}mm @ ${state.tieSpacing.toInt()}mm c/c',
        ],
      ]),
      pw.SizedBox(height: 10),
      _buildOptimizationSection(
        _optimizationEngine.optimizeColumnSection(
          pu: state.pu,
          mx: state.mx,
          my: state.my,
          concreteGrade: state.concreteGrade,
          steelGrade: state.steelGrade,
          length: state.length,
        ),
      ),
      pw.SizedBox(height: 20),
      pw.Center(child: _buildColumnDiagram(state)),
    ];

    await generateAndShare(
      title: 'Column Design Report',
      subtitle: 'Reinforced Concrete Structural Analysis',
      content: content,
      projectName: 'SiteBuddy Engineering',
      reference: 'CL-${DateTime.now().year}-${math.Random().nextInt(1000)}',
    );
  }

  static pw.Widget _buildColumnDiagram(ColumnDesignState state) {
    return pw.Container(
      width: 200,
      height: 200,
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300, width: 0.5),
      ),
      child: pw.CustomPaint(
        size: const PdfPoint(200, 200),
        painter: (canvas, size) {
          final isCircular = state.type == ColumnType.circular;
          const padding = 20.0;
          final drawWidth = size.x - 2 * padding;
          final drawHeight = size.y - 2 * padding;

          // Draw Section Outline
          canvas.setStrokeColor(PdfColors.black);
          canvas.setLineWidth(2);
          if (isCircular) {
            canvas.drawEllipse(
              size.x / 2,
              size.y / 2,
              drawWidth / 2,
              drawHeight / 2,
            );
          } else {
            // Rectangular
            double aspect = state.b / state.d;
            double w = drawWidth;
            double h = drawHeight;
            if (aspect > 1) {
              h = w / aspect;
            } else {
              w = h * aspect;
            }
            canvas.drawRect(size.x / 2 - w / 2, size.y / 2 - h / 2, w, h);
          }
          canvas.strokePath();

          // Draw Rebar
          canvas.setFillColor(PdfColors.black);
          const barRadius = 3.0;

          if (isCircular) {
            final radius = (drawWidth / 2) - 10;
            final cx = size.x / 2;
            final cy = size.y / 2;
            for (int i = 0; i < state.numBars; i++) {
              final angle = (2 * math.pi * i) / state.numBars;
              final x = cx + radius * math.cos(angle);
              final y = cy + radius * math.sin(angle);
              canvas.drawEllipse(x, y, barRadius, barRadius);
              canvas.fillPath();
            }
          } else {
            // Rectangular
            double aspect = state.b / state.d;
            double w = drawWidth;
            double h = drawHeight;
            if (aspect > 1) {
              h = w / aspect;
            } else {
              w = h * aspect;
            }

            final rectX = size.x / 2 - w / 2;
            final rectY = size.y / 2 - h / 2;
            final innerW = w - 10;
            final innerH = h - 10;
            final ix = rectX + 5;
            final iy = rectY + 5;

            // Simplified bar placement (4 corners + rest along edges)
            final bars = <PdfPoint>[];
            bars.add(PdfPoint(ix, iy));
            bars.add(PdfPoint(ix + innerW, iy));
            bars.add(PdfPoint(ix, iy + innerH));
            bars.add(PdfPoint(ix + innerW, iy + innerH));

            if (state.numBars > 4) {
              int remaining = state.numBars - 4;
              int perSideX = (remaining / 2).ceil();
              for (int i = 1; i <= perSideX; i++) {
                double xOffset = (innerW / (perSideX + 1)) * i;
                bars.add(PdfPoint(ix + xOffset, iy));
                bars.add(PdfPoint(ix + xOffset, iy + innerH));
              }
            }

            for (var p in bars.take(state.numBars)) {
              canvas.drawEllipse(p.x, p.y, barRadius, barRadius);
              canvas.fillPath();
            }
          }
        },
      ),
    );
  }

  static Future<void> generateBeamReport(BeamDesignState state) async {
    final content = [
      sectionTitle('1. Input Parameters'),
      infoTable([
        ['Beam Type', 'Span', 'Width', 'Depth'],
        [
          state.type.label,
          '${(state.span / 1000).toStringAsFixed(2)} m',
          '${state.width.toInt()} mm',
          '${state.overallDepth.toInt()} mm',
        ],
      ]),
      pw.SizedBox(height: 10),
      infoTable([
        ['Concrete Grade', 'Steel Grade', 'Clear Cover'],
        [state.concreteGrade, state.steelGrade, '${state.cover} mm'],
      ]),
      sectionTitle('2. Applied Loads (Factored)'),
      infoTable([
        ['Dead Load', 'Live Load', 'Point Load'],
        [
          '${state.deadLoad} kN/m',
          '${state.liveLoad} kN/m',
          '${state.pointLoad} kN',
        ],
      ]),
      sectionTitle('3. Analysis Results'),
      infoTable([
        ['Resultant Moment (Mu)', 'Resultant Shear (Vu)', 'ULS Case'],
        [
          '${state.mu.toStringAsFixed(2)} kNm',
          '${state.vu.toStringAsFixed(2)} kN',
          state.isULS ? 'Yes' : 'No',
        ],
      ]),
      sectionTitle('4. Reinforcement Design'),
      infoTable([
        ['Main Reinforcement', 'Provided Ast', 'Neutral Axis Ratio'],
        [
          '${state.numBars} Nos ${state.mainBarDia.toInt()}mm dia',
          '${state.astProvided.toInt()} mm²',
          (state.xu / state.xuMax).toStringAsFixed(3),
        ],
      ]),
      pw.SizedBox(height: 10),
      infoTable([
        ['Stirrups (Shear)', 'Spacing'],
        [
          '${state.stirrupLegs} legged ${state.stirrupDia.toInt()}mm',
          '${state.stirrupSpacing.toInt()} mm c/c',
        ],
      ]),
      sectionTitle('5. Safety Verification'),
      pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
        children: [
          safetyBadge(
            state.isFlexureSafe,
            'FLEXURE: ${state.isFlexureSafe ? "SAFE" : "FAIL"}',
          ),
          safetyBadge(
            state.isShearSafe,
            'SHEAR: ${state.isShearSafe ? "SAFE" : "FAIL"}',
          ),
          safetyBadge(
            state.isDeflectionSafe,
            'DEFLECTION: ${state.isDeflectionSafe ? "SAFE" : "FAIL"}',
          ),
        ],
      ),
      pw.SizedBox(height: 10),
      _buildOptimizationSection(
        _optimizationEngine.optimizeBeamSection(
          span: state.span,
          deadLoad: state.deadLoad,
          liveLoad: state.liveLoad,
          concreteGrade: state.concreteGrade,
          steelGrade: state.steelGrade,
          type: state.type,
        ),
      ),
      pw.SizedBox(height: 20),
      pw.Center(child: _buildBeamDiagram(state)),
    ];

    await generateAndShare(
      title: 'Beam Design Report',
      subtitle: 'RC Beam Structural Calculation Sheet',
      content: content,
      projectName: 'SiteBuddy Engineering',
      reference: 'BM-${DateTime.now().year}-${math.Random().nextInt(1000)}',
    );
  }

  static pw.Widget _buildBeamDiagram(BeamDesignState state) {
    return pw.Container(
      width: 250,
      height: 180,
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300, width: 0.5),
      ),
      child: pw.CustomPaint(
        size: const PdfPoint(250, 180),
        painter: (canvas, size) {
          const padding = 40.0;
          final drawWidth = size.x - 2 * padding;
          final drawHeight = size.y - 2 * padding;

          final cx = size.x / 2;
          final cy = size.y / 2;

          // Draw Section
          canvas.setStrokeColor(PdfColors.black);
          canvas.setLineWidth(1.5);
          canvas.drawRect(
            cx - drawWidth / 2,
            cy - drawHeight / 2,
            drawWidth,
            drawHeight,
          );
          canvas.strokePath();

          // Stirrup
          canvas.setStrokeColor(PdfColors.grey700);
          canvas.setLineWidth(1);
          const sPadding = 5.0;
          canvas.drawRect(
            cx - drawWidth / 2 + sPadding,
            cy - drawHeight / 2 + sPadding,
            drawWidth - 2 * sPadding,
            drawHeight - 2 * sPadding,
          );
          canvas.strokePath();

          // Main Bars (Bottom)
          canvas.setFillColor(PdfColors.black);
          const barRadius = 2.5;
          final rebarY = cy + drawHeight / 2 - 10;
          final startX = cx - drawWidth / 2 + 10;
          final endX = cx + drawWidth / 2 - 10;

          for (int i = 0; i < state.numBars; i++) {
            final x = state.numBars > 1
                ? startX + (endX - startX) * (i / (state.numBars - 1))
                : cx;
            canvas.drawEllipse(x, rebarY, barRadius, barRadius);
            canvas.fillPath();
          }

          // Hanger Bars (Top)
          canvas.drawEllipse(
            startX,
            cy - drawHeight / 2 + 10,
            barRadius,
            barRadius,
          );
          canvas.drawEllipse(
            endX,
            cy - drawHeight / 2 + 10,
            barRadius,
            barRadius,
          );
          canvas.fillPath();
        },
      ),
    );
  }

  static Future<void> generateSlabReport(SlabDesignState state) async {
    final content = [
      sectionTitle('1. Slab Parameters'),
      infoTable([
        ['Slab Type', 'Dimensions (Lx x Ly)', 'Overall Depth (D)'],
        [
          state.type.label,
          '${state.lx} m x ${state.ly} m',
          '${state.d.toInt()} mm',
        ],
      ]),
      pw.SizedBox(height: 10),
      infoTable([
        ['Dead Load (Incl. Finish)', 'Live Load (Imposed)'],
        ['${state.deadLoad} kN/m²', '${state.liveLoad} kN/m²'],
      ]),
      sectionTitle('2. Design Results'),
      if (state.result != null) ...[
        infoTable([
          ['Design Moment (Mu)', 'Main Reinforcement', 'Distribution Steel'],
          [
            '${state.result!.bendingMoment.toStringAsFixed(2)} kNm/m',
            state.result!.mainRebar,
            state.result!.distributionSteel,
          ],
        ]),
        sectionTitle('3. Safety Verification'),
        pw.Row(
          mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
          children: [
            safetyBadge(
              state.result!.isShearSafe,
              'SHEAR: ${state.result!.isShearSafe ? "SAFE" : "FAIL"}',
            ),
            safetyBadge(
              state.result!.isDeflectionSafe,
              'DEFLECTION: ${state.result!.isDeflectionSafe ? "SAFE" : "FAIL"}',
            ),
            safetyBadge(
              state.result!.isCrackingSafe,
              'CRACKING: ${state.result!.isCrackingSafe ? "SAFE" : "FAIL"}',
            ),
          ],
        ),
      ] else
        pw.Center(
          child: pw.Text(
            'No design results available. Please run calculations first.',
            style: const pw.TextStyle(color: PdfColors.red),
          ),
        ),
      pw.SizedBox(height: 10),
      _buildOptimizationSection(
        _optimizationEngine.optimizeSlabThickness(
          lx: state.lx,
          ly: state.ly,
          deadLoad: state.deadLoad,
          liveLoad: state.liveLoad,
          type: state.type,
        ),
      ),
      pw.SizedBox(height: 20),
      pw.Center(child: _buildSlabDiagram(state)),
    ];

    await generateAndShare(
      title: 'Slab Design Report',
      subtitle: 'Reinforced Concrete Slab Analysis',
      content: content,
      projectName: 'SiteBuddy Engineering',
      reference: 'SL-${DateTime.now().year}-${math.Random().nextInt(1000)}',
    );
  }

  static Future<void> generateFootingReport(FootingDesignState state) async {
    final content = [
      sectionTitle('1. Input & Soil Parameters'),
      infoTable([
        ['Footing Type', 'Safe Bearing Capacity', 'Found. Depth'],
        [state.type.label, '${state.sbc} kN/m²', '${state.foundationDepth} m'],
      ]),
      pw.SizedBox(height: 10),
      infoTable([
        ['Vertical Load (Pu)', 'Concrete Grade', 'Steel Grade'],
        ['${state.columnLoad} kN', state.concreteGrade, state.steelGrade],
      ]),
      sectionTitle('2. Geometrical Design'),
      infoTable([
        ['Length (L)', 'Width (B)', 'Thickness (D)', 'Provided Area'],
        [
          '${state.footingLength.toInt()} mm',
          '${state.footingWidth.toInt()} mm',
          '${state.footingThickness.toInt()} mm',
          '${(state.providedArea).toStringAsFixed(2)} m',
        ],
      ]),
      sectionTitle('3. Pressure & Shear Analysis'),
      infoTable([
        ['Max Pressure (q_max)', 'Factored Net (qu)', 'Effective Depth'],
        [
          '${state.maxSoilPressure.toStringAsFixed(2)} kN/m²',
          '${state.qu.toStringAsFixed(2)} kN/m²',
          '${state.effDepth.toInt()} mm',
        ],
      ]),
      sectionTitle('4. Reinforcement Details'),
      infoTable([
        ['Direction', 'Required Ast', 'Provided Steel'],
        [
          'X-Direction',
          '${state.astRequiredX.toInt()} mm²',
          '${state.mainBarDia.toInt()}mm @ ${state.mainBarSpacing.toInt()}mm',
        ],
        [
          'Y-Direction',
          '${state.astRequiredY.toInt()} mm²',
          '${state.crossBarDia.toInt()}mm @ ${state.crossBarSpacing.toInt()}mm',
        ],
      ]),
      sectionTitle('5. Safety Verification'),
      pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
        children: [
          safetyBadge(
            state.isAreaSafe,
            'AREA: ${state.isAreaSafe ? "SAFE" : "FAIL"}',
          ),
          safetyBadge(
            state.isOneWayShearSafe,
            '1-WAY SHEAR: ${state.isOneWayShearSafe ? "SAFE" : "FAIL"}',
          ),
          safetyBadge(
            state.isPunchingShearSafe,
            'PUNCHING: ${state.isPunchingShearSafe ? "SAFE" : "FAIL"}',
          ),
        ],
      ),
      pw.SizedBox(height: 10),
      _buildOptimizationSection(
        _optimizationEngine.optimizeFootingSize(
          columnLoad: state.columnLoad,
          sbc: state.sbc,
          concreteGrade: state.concreteGrade,
          steelGrade: state.steelGrade,
          momentX: state.momentX,
          momentY: state.momentY,
        ),
      ),
      pw.SizedBox(height: 20),
      pw.Center(child: _buildFootingDiagram(state)),
    ];

    await generateAndShare(
      title: 'Footing Design Report',
      subtitle: 'Shallow Foundation Design Calculation',
      content: content,
      projectName: 'SiteBuddy Engineering',
      reference: 'FT-${DateTime.now().year}-${math.Random().nextInt(1000)}',
    );
  }

  static pw.Widget _buildSlabDiagram(SlabDesignState state) {
    return pw.Container(
      width: 250,
      height: 150,
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300, width: 0.5),
      ),
      child: pw.CustomPaint(
        size: const PdfPoint(250, 150),
        painter: (canvas, size) {
          final cx = size.x / 2;
          final cy = size.y / 2;
          final w = 180.0;
          final h = 100.0;

          // Slab Body
          canvas.setStrokeColor(PdfColors.black);
          canvas.setLineWidth(1.5);
          canvas.drawRect(cx - w / 2, cy - h / 2, w, h);
          canvas.strokePath();

          // Main Rebar (Horizontal dashes)
          canvas.setStrokeColor(PdfColors.black);
          canvas.setLineWidth(1);
          for (int i = 0; i < 5; i++) {
            final y = cy - h / 2 + 15 + i * 18;
            canvas.drawLine(cx - w / 2 + 5, y, cx + w / 2 - 5, y);
          }
          canvas.strokePath();

          // Distribution (Vertical dots/lines)
          canvas.setStrokeColor(PdfColors.grey600);
          for (int i = 0; i < 8; i++) {
            final x = cx - w / 2 + 20 + i * 20;
            canvas.drawLine(x, cy - h / 2 + 5, x, cy + h / 2 - 5);
          }
          canvas.strokePath();
        },
      ),
    );
  }

  static pw.Widget _buildFootingDiagram(FootingDesignState state) {
    return pw.Container(
      width: 200,
      height: 200,
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300, width: 0.5),
      ),
      child: pw.CustomPaint(
        size: const PdfPoint(200, 200),
        painter: (canvas, size) {
          final cx = size.x / 2;
          final cy = size.y / 2;
          final fSize = 150.0;

          // Footing Outline
          canvas.setStrokeColor(PdfColors.black);
          canvas.setLineWidth(1.5);
          canvas.drawRect(cx - fSize / 2, cy - fSize / 2, fSize, fSize);
          canvas.strokePath();

          // Column Outline
          final cSize = 40.0;
          canvas.drawRect(cx - cSize / 2, cy - cSize / 2, cSize, cSize);
          canvas.strokePath();

          // Rebar Grid
          canvas.setStrokeColor(PdfColors.grey500);
          canvas.setLineWidth(0.5);
          for (int i = 0; i < 6; i++) {
            final offset = -fSize / 2 + 20 + i * 22;
            canvas.drawLine(
              cx - fSize / 2 + 10,
              cy + offset,
              cx + fSize / 2 - 10,
              cy + offset,
            );
            canvas.drawLine(
              cx + offset,
              cy - fSize / 2 + 10,
              cx + offset,
              cy + fSize / 2 - 10,
            );
          }
          canvas.strokePath();
        },
      ),
    );
  }
}
