import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

/// SERVICE: DrawingExportService
/// PURPOSE: Handles capturing structural drawings as images and PDF documents. (Pure Logic)
class DrawingExportService {
  /// Prepares drawing bytes for export (Placeholder for future processing)
  static Uint8List prepareImage(Uint8List pngBytes) {
    return pngBytes;
  }

  /// Exports a captured image (bytes) into a professional PDF document bytes.
  static Future<Uint8List> generateDrawingPdf(
    Uint8List pngBytes,
    String title,
    String subtitle,
  ) async {
    if (pngBytes.isEmpty) {
      throw Exception('Empty image bytes provided to PDF generator.');
    }

    final pdf = pw.Document();
    final imageWidget = pw.MemoryImage(pngBytes);

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                title,
                style: pw.TextStyle(
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 8),
              pw.Text(
                subtitle,
                style: const pw.TextStyle(
                  fontSize: 14,
                  color: PdfColors.grey700,
                ),
              ),
              pw.Divider(),
              pw.SizedBox(height: 20),
              pw.Center(child: pw.Image(imageWidget)),
              pw.Spacer(),
              pw.Divider(),
              pw.Text(
                'Generated by SiteBuddy Structural Toolkit',
                style: const pw.TextStyle(
                  fontSize: 10,
                  color: PdfColors.grey500,
                ),
              ),
            ],
          );
        },
      ),
    );

    return pdf.save();
  }
}



