import 'package:site_buddy/shared/domain/models/design/beam_type.dart';

/// MODEL: BeamInput
/// Data structure for all inputs required to perform a beam design.
class BeamInput {
  final BeamType type;
  final double span; // in mm
  final double width; // in mm
  final double overallDepth; // in mm
  final double cover; // in mm
  final String concreteGrade;
  final String steelGrade;
  final double deadLoad; // in kN/m
  final double liveLoad; // in kN/m
  final double pointLoad; // in kN

  const BeamInput({
    required this.type,
    required this.span,
    required this.width,
    required this.overallDepth,
    required this.cover,
    required this.concreteGrade,
    required this.steelGrade,
    required this.deadLoad,
    required this.liveLoad,
    this.pointLoad = 0,
  });
}

/// MODEL: BeamResult
/// Data structure for all outputs generated by an RCC beam design.
class BeamResult {
  final double bendingMoment;
  final double shearForce;
  final String topRebar;
  final String bottomRebar;
  final String stirrups;
  final bool isFlexureSafe;
  final bool isShearSafe;
  final bool isDeflectionSafe;

  const BeamResult({
    required this.bendingMoment,
    required this.shearForce,
    required this.topRebar,
    required this.bottomRebar,
    required this.stirrups,
    required this.isFlexureSafe,
    required this.isShearSafe,
    required this.isDeflectionSafe,
  });
}
