class EngineeringTerms {
  EngineeringTerms._();

  static const length = 'Length';
  static const width = 'Width';
  static const depth = 'Depth';
  static const height = 'Height';
  static const lengthHint = 'e.g. 5.0';
  static const widthHint = 'e.g. 0.3';
  static const depthHint = 'e.g. 0.6';
  static const heightHint = 'e.g. 3.0';
  static const areaHint = 'e.g. 20.0';
  static const spacingHint = 'e.g. 0.15';
  static const diameterHint = 'e.g. 12';
  static const steelRatioHint = '1%';
  static const wasteFactorHint = '5%';
  static const steelRatio = 'Steel Ratio';
  static const wasteFactor = 'Waste Factor';

  static const wallDimensions = 'Wall Dimensions';
  static const wallLength = 'Wall Length (m)';
  static const wallHeight = 'Wall Height (m)';
  static const wallThickness = 'Wall Thickness (m)';
  static const brickAndMortar = 'Brick & Mortar';
  static const brickSize = 'Brick Size';
  static const standardBrickSize = '190 × 90 × 90 mm  (IS modular standard)';
  static const brickWithJoint = 'With 10 mm mortar joint: 200 × 100 × 100 mm';
  static const brickStandardRef = 'IS 2212:1991 standard brick dimensions';
  static const brickInfo = 'IS modular brick: 190×90×90 mm (without joint).\nCustom brick sizes coming soon.';
  static const mortarRatio = 'MORTAR RATIO';
  static const resultSummary = 'RESULT SUMMARY';
  static const numberOfBricks = 'Number of Bricks';
  static const brickVolume = 'Brick Volume';
  static const cementBags = 'Cement Bags (50 kg)';
  static const sandVolume = 'Sand Volume';
  static const thicknessLabel = 'Thickness:';
  static const wallVolume = 'Wall Volume';
  static const mortarRatioLabel = 'Mortar Ratio:';
  static const brickMasonryRef = 'Calculations per IS 2212:1991 (Brick masonry code of practice).\nIS modular brick: 190 × 90 × 90 mm · Joint: 10 mm · Wastage: 5%.\nMortar dry volume factor: 1.30 · Cement density: 1440 kg/m³.';

  static const wetVolume = 'Wet Volume';
  static const dryVolume = 'Dry Volume';
  static const cementWeight = 'Cement Weight';
  static const numberOfBags = 'Number of Bags';
  static const estimatedCost = 'Estimated Cost';
  static const volumeAndDimensions = 'VOLUME & DIMENSIONS';
  static const ratioFormat = 'MIX RATIO (CEMENT : SAND : AGG)';
  static const cement = 'Cement';
  static const sand = 'Sand';
  static const aggregate = 'Aggregate';
  static const wastePercent = 'Waste (%)';
  static const pricePerBag = 'Price per Bag';
  static const cementRatioInfo = 'Cement part of the ratio (e.g., 1)';
  static const sandRatioInfo = 'Sand part of the ratio (e.g., 2)';
  static const aggregateRatioInfo = 'Aggregate part of the ratio (e.g., 4)';
  static const wasteInfo = 'Percentage of material expected to be lost during application';

  static const pitDimensions = 'Pit Dimensions';
  static const parameters = 'Parameters';
  static const clearance = 'Clearance (m)';
  static const swellFactor = 'Swell Factor';
  static const clearanceInfo = 'Extra space added around the pit for working room (IS 3764).';
  static const swellFactorInfo = 'Ratio of loose volume to bank volume. 1.25 for typical soil.';
  static const totalVolumeLoose = 'Total Volume (Loose)';
  static const bankVolumeNatural = 'Bank Volume (Natural)';
  static const clearanceLabel = 'Clearance:';
  static const swellFactorLabel = 'Swell Factor:';

  static const flat = 'FLAT';
  static const mild = 'MILD';
  static const moderate = 'MODERATE';
  static const steep = 'STEEP';
  static const percentage = 'Percentage';
  static const ratio = 'Ratio';
  static const angle = 'Angle';
  static const classification = 'CLASSIFICATION';
  static const slopeVisualization = 'SLOPE VISUALIZATION';
  static const slopeCalculator = 'Slope & Gradient Calculator';
  static const verticalRise = 'Vertical Rise (m)';
  static const horizontalRun = 'Horizontal Run (m)';
  static const fieldReference = 'FIELD REFERENCE';
  static const sewerPipes = 'Sewer Pipes';
  static const roadCrossFall = 'Road Cross Fall';
  static const wheelchairRamp = 'Wheelchair Ramp';
  static const earthworksBatter = 'Earthworks Batter';
  static const sewerPipesRef = '1:100 to 1:200';
  static const roadCrossFallRef = '2% to 3%';
  static const wheelchairRampRef = '1:12 (max 1:8)';
  static const earthworksBatterRef = '1:2 to 1:4';
  static const vertical = 'Vertical';

  static const concreteGrade = 'CONCRETE GRADE';
  static const dimensions = 'Dimensions';
  static const thicknessDepth = 'Thickness / Depth (m)';
  static const reinforcementAndWaste = 'Reinforcement & Waste';
  static const steelRatioPercent = 'Steel Ratio (%)';
  static const wasteFactorPercent = 'Waste Factor (%)';
  static const concreteVolume = 'Concrete Volume';
  static const aggregateVolume = 'Aggregate Volume';
  static const steelWeight = 'Steel Weight';
  static const bindingWire = 'Binding Wire (≈1%)';
  static const steelRatioZeroNote = 'Steel ratio set to 0 — plain concrete (PCC) assumed.';
  static const mixGradeLabel = 'Mix Grade:';
  static const concreteCodeRef = 'Calculations per IS 456:2000 (nominal volume proportioning).\nDry volume factor: 1.54 for concrete · 1.30 for mortar (IS 2212:1991).\nSteel density: 7850 kg/m³ (IS 1786).';

  static const plasterArea = 'Plaster Area';
  static const wallArea = 'Wall Area (m²)';
  static const plasterThickness = 'Plaster Thickness (mm)';
  static const typicalThicknessNote = 'Note: Typical internal: 12mm · External: 15-20mm · Ceiling: 6mm';
  static const dryMortarVolume = 'Dry Mortar Volume';
  static const plasterEstimator = 'Plaster Material Estimator';
  static const calculateMaterials = 'Calculate Materials';
  static const isPlasterCodeNote = 'Calculations per IS 2212:1991 (Plastering code of practice).\nDry volume factor: 1.30 for mortar · Wastage: 10% · Joint filling: 5% included.';
  static const levelCalculator = 'Level Calculator';
  static const gradientTool = 'Gradient Tool';

  static const rise = 'RISE';
  static const fall = 'FALL';
  static const absoluteDifference = 'Absolute Difference';
  static const fieldLevelComparison = 'Field Level Comparison';
  static const startLevel = 'Start Level (m)';
  static const endLevel = 'End Level (m)';

  static const totalLength = 'Total Length';
  static const totalWeight = 'Total Weight';
  static const numberOfBars = 'Number of Bars';
  static const rebarRequirements = 'STRUCTURAL REBAR REQUIREMENTS';
  static const memberLength = 'Member Length (m)';
  static const spacingLabel = 'Spacing (m)';
  static const diameterLabel = 'Diameter (mm)';
  static const sandCubicFeet = 'Sand (ft³)';
  static const volumeAndRate = 'VOLUME & RATE';
  static const ratePerUnit = 'Rate per m³ (optional)';
  static const sandQuantityEstimator = 'Sand Quantity Estimator';

  static const shutteringAreaEstimator = 'Shuttering Area Estimator';
  static const elementDimensions = 'Element Dimensions';
  static const includeBottomArea = 'Include Bottom Area?';
  static const shutteringNote = 'Estimation for simple beams, slabs, or footings.\nArea = 2 × (Length + Width) × Depth + Optional Bottom.';
  static const totalShutteringArea = 'Total Shuttering Area';
  static const perimeter = 'Perimeter';
  static const brickThicknessHint = 'e.g. 0.23 for 9-inch';
  static const pitLengthHint = 'e.g. 2.0';
  static const pitDepthHint = 'e.g. 1.5';
  static const swellFactorHint = 'e.g. 1.25';
  static const aiAssistant = 'AI Assistant';
}
