import 'package:site_buddy/features/structural/column/domain/column_enums.dart';

/// MODEL: ColumnInput
/// Data structure for all inputs required to perform a column design.
class ColumnInput {
  final ColumnType type;
  final double b; // Width or Diameter in mm
  final double d; // Depth (for rectangular) in mm
  final double length; // in mm
  final EndCondition endCondition;
  final double cover; // in mm
  final String concreteGrade;
  final String steelGrade;
  final double pu; // Factored Axial Load in kN
  final double mx; // Factored Moment X in kNm
  final double my; // Factored Moment Y in kNm
  final double mainBarDia; // in mm
  final double steelPercentage; // 0.8 to 6.0
  final bool isAutoSteel;

  const ColumnInput({
    required this.type,
    required this.b,
    this.d = 0,
    required this.length,
    required this.endCondition,
    required this.cover,
    required this.concreteGrade,
    required this.steelGrade,
    required this.pu,
    this.mx = 0,
    this.my = 0,
    this.mainBarDia = 12.0,
    this.steelPercentage = 1.0,
    this.isAutoSteel = true,
  });
}

/// MODEL: ColumnResult
/// Data structure for all outputs generated by an RCC column design.
class ColumnResult {
  final String reinforcement;
  final String ties;
  final double interactionRatio;
  final bool isCapacitySafe;
  final bool isSlendernessSafe;
  final double lex;
  final double ley;
  final double slendernessX;
  final double slendernessY;
  final double eminX;
  final double eminY;
  final double magnifiedMx;
  final double magnifiedMy;
  final bool isShort;
  final double ag;
  final double astRequired;
  final int numBars;
  final double tieSpacing;
  final double tieDia;
  final ColumnFailureMode failureMode;
  final bool isReinforcementSafe;

  const ColumnResult({
    required this.reinforcement,
    required this.ties,
    required this.interactionRatio,
    required this.isCapacitySafe,
    required this.isSlendernessSafe,
    this.lex = 0,
    this.ley = 0,
    this.slendernessX = 0,
    this.slendernessY = 0,
    this.eminX = 0,
    this.eminY = 0,
    this.magnifiedMx = 0,
    this.magnifiedMy = 0,
    this.isShort = true,
    this.ag = 0,
    this.astRequired = 0,
    this.numBars = 0,
    this.tieSpacing = 0,
    this.tieDia = 0,
    this.failureMode = ColumnFailureMode.axial,
    this.isReinforcementSafe = true,
  });
}

/// INTERNAL: ColumnAnalysis
/// Intermediate data for slenderness and initial analysis.
class ColumnAnalysis {
  final double lex;
  final double ley;
  final double slendernessX;
  final double slendernessY;
  final bool isShort;
  final bool isSlendernessSafe;
  final double eminX;
  final double eminY;
  final double magnifiedMx;
  final double magnifiedMy;

  const ColumnAnalysis({
    required this.lex,
    required this.ley,
    required this.slendernessX,
    required this.slendernessY,
    required this.isShort,
    required this.isSlendernessSafe,
    required this.eminX,
    required this.eminY,
    required this.magnifiedMx,
    required this.magnifiedMy,
  });
}

/// INTERNAL: ColumnCapacity
/// Intermediate data for capacity and interaction.
class ColumnCapacity {
  final double ag;
  final double astRequired;
  final double interactionRatio;
  final bool isCapacitySafe;
  final ColumnFailureMode failureMode;

  const ColumnCapacity({
    required this.ag,
    required this.astRequired,
    required this.interactionRatio,
    required this.isCapacitySafe,
    required this.failureMode,
  });
}

