/// FILE HEADER
/// ----------------------------------------------
/// File: share_helper.dart
/// Feature: core/utils
/// Layer: utilities
///
/// PURPOSE:
/// Provides a unified, high-level API for triggering system share dialogs
/// with professionally formatted engineering content.
/// ----------------------------------------------
library;


import 'package:flutter/foundation.dart';
import 'package:intl/intl.dart';
import 'package:share_plus/share_plus.dart';

/// CLASS: ShareHelper
/// PURPOSE: Static utility to handle system share requests.
class ShareHelper {
  /// METHOD: shareSlabDesign
  /// PURPOSE: Triggers a system share for a Slab Design report.
  static Future<void> shareSlabDesign({
    required String projectName,
    required String slabType,
    required double lx,
    required double ly,
    required double depth,
    required double deadLoad,
    required double liveLoad,
    required double totalLoad,
    required double bendingMoment,
    required String mainRebar,
    required String distributionSteel,
  }) async {
    final date = DateFormat('dd MMM yyyy').format(DateTime.now());

    final content =
        '''
Project: $projectName
Date: $date

Slab Type: $slabType
Span: $lx × $ly m
Effective Depth: ${depth.toStringAsFixed(0)} mm

Loads:
- Dead Load: ${deadLoad.toStringAsFixed(2)} kN/m²
- Live Load: ${liveLoad.toStringAsFixed(2)} kN/m²
- Total Load: ${totalLoad.toStringAsFixed(2)} kN/m²

Design Results:
- Bending Moment: ${bendingMoment.toStringAsFixed(2)} kNm/m
- Main Reinforcement: $mainRebar
- Distribution Steel: $distributionSteel

Checks:
✔ Shear: OK
✔ Deflection: OK
✔ Cracking: OK

----------------------------------------
Generated by Site Buddy
----------------------------------------
''';

    try {
      await SharePlus.instance.share(ShareParams(text: content));
    } catch (e) {
      debugPrint('ERROR: Native share failed: $e');
    }
  }

  /// METHOD: shareXFile
  /// PURPOSE: Shares a file (e.g., image) using XFile.
  static Future<void> shareXFile({
    required Uint8List bytes,
    required String name,
    required String mimeType,
    String? subject,
  }) async {
    try {
      final xFile = XFile.fromData(bytes, name: name, mimeType: mimeType);
      await SharePlus.instance.share(ShareParams(files: [xFile]));
    } catch (e) {
      debugPrint('ERROR: Native file share failed: $e');
    }
  }
}



