/// FILE HEADER
/// ----------------------------------------------
/// File: share_formatter.dart
/// Feature: core/utils
/// Layer: utilities
///
/// PURPOSE:
/// Formats standardized AI responses into a user-friendly structured string for native sharing.
///
/// RESPONSIBILITIES:
/// - Provides a static `format` method.
/// - Injects watermarked branding into shared content natively.
/// ----------------------------------------------
library;


import 'package:intl/intl.dart';

class ShareFormatter {
  /// METHOD: format
  /// PURPOSE: Converts dynamic UI structures into an official text-based report format.
  /// WHY: Centralizes share formatting to avoid business logic inside UI controllers.
  static String format({
    required String question,
    required String answer,
    required String projectName,
  }) {
    return '''
----------------------------------------
SITE BUDDY REPORT
Project: $projectName
Date: ${_formattedDate()}
----------------------------------------

Question:
$question

Answer:
$answer

----------------------------------------
Generated by Site Buddy
Developed by Er. Pijush Debbarma
----------------------------------------
''';
  }

  /// METHOD: _formattedDate
  /// PURPOSE: Internal helper to generate a standardized report date.
  static String _formattedDate() {
    return DateFormat('dd MMM yyyy').format(DateTime.now());
  }
}



