/// FILE HEADER
/// ----------------------------------------------
/// File: share_image_generator.dart
/// Feature: core/utils
/// Layer: utilities
///
/// PURPOSE:
/// Captures a rendered Widget visually and exports it as an image file.
///
/// RESPONSIBILITIES:
/// - Transforms a `GlobalKey` belonging to a `RepaintBoundary` into a PNG.
/// - Saves the file temporarily and returns an `XFile` that `share_plus` can consume natively.
/// ----------------------------------------------
library;


import 'dart:io';
import 'dart:ui' as ui;
import 'package:flutter/material.dart';
import 'package:flutter/rendering.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

class ShareImageGenerator {
  /// METHOD: generateAndShareImage
  /// PURPOSE: Converts a RepaintBoundary to a PNG and opens the native share dialog.
  /// WHY: Abstracting this logic out of Presenters prevents heavy I/O operations from freezing state logic.
  static Future<void> generateAndShareImage(
    GlobalKey boundaryKey,
    String defaultFilename,
  ) async {
    try {
      final boundary =
          boundaryKey.currentContext?.findRenderObject()
              as RenderRepaintBoundary?;
      if (boundary == null) return;

      final ui.Image image = await boundary.toImage(pixelRatio: 3.0);
      final byteData = await image.toByteData(format: ui.ImageByteFormat.png);
      if (byteData == null) return;

      final pngBytes = byteData.buffer.asUint8List();
      final directory = await getApplicationDocumentsDirectory();
      final file = File('${directory.path}/$defaultFilename.png');
      await file.writeAsBytes(pngBytes);

      // ignore: deprecated_member_use
      final result = await Share.shareXFiles([
        XFile(file.path),
      ], text: 'Generated by Site Buddy');

      if (result.status == ShareResultStatus.success) {
        debugPrint("Successfully shared image.");
      }
    } catch (e) {
      debugPrint("Error sharing image: \$e");
    }
  }
}



